// ─── Application Constants ───────────────────────────────────────────────────

export const APP_NAME = 'Exponent';
export const APP_DESCRIPTION = 'AI-Powered Indian Stock Market Platform';

export const NIFTY_50_STOCKS = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Oil & Gas' },
  { symbol: 'TCS', name: 'Tata Consultancy', sector: 'IT' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'ITC', name: 'ITC', sector: 'FMCG' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Infrastructure' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Paints' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharma', sector: 'Pharma' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Power' },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Power' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'ONGC', name: 'ONGC', sector: 'Oil & Gas' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', sector: 'Infrastructure' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'DRREDDY', name: "Dr Reddy's Labs", sector: 'Pharma' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Finance' },
  { symbol: 'DIVISLAB', name: "Divi's Labs", sector: 'Pharma' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Cement' },
  { symbol: 'BPCL', name: 'BPCL', sector: 'Oil & Gas' },
  { symbol: 'SHREECEM', name: 'Shree Cement', sector: 'Cement' },
  { symbol: 'BRITANNIA', name: 'Britannia', sector: 'FMCG' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life', sector: 'Insurance' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer', sector: 'FMCG' },
  { symbol: 'M_M', name: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'LTIM', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'HINDALCO', name: 'Hindalco', sector: 'Metals' },
  { symbol: 'BAJAJ_AUTO', name: 'Bajaj Auto', sector: 'Auto' },
];

export const SECTORS = [
  'IT', 'Banking', 'FMCG', 'Pharma', 'Auto', 'Oil & Gas',
  'Metals', 'Infrastructure', 'Finance', 'Power', 'Cement',
  'Telecom', 'Consumer', 'Insurance', 'Healthcare', 'Mining',
  'Conglomerate', 'Paints',
];

export const SECTOR_COLORS: Record<string, string> = {
  IT: '#06b6d4',
  Banking: '#8b5cf6',
  FMCG: '#f59e0b',
  Pharma: '#10b981',
  Auto: '#ef4444',
  'Oil & Gas': '#f97316',
  Metals: '#6366f1',
  Infrastructure: '#ec4899',
  Finance: '#14b8a6',
  Power: '#eab308',
  Cement: '#94a3b8',
  Telecom: '#06b6d4',
  Consumer: '#a855f7',
  Insurance: '#22c55e',
  Healthcare: '#3b82f6',
  Mining: '#78716c',
  Conglomerate: '#d946ef',
  Paints: '#fb923c',
};

export const CHART_PERIODS = [
  { label: '1D', value: '1D' },
  { label: '1W', value: '1W' },
  { label: '1M', value: '1M' },
  { label: '3M', value: '3M' },
  { label: '6M', value: '6M' },
  { label: '1Y', value: '1Y' },
  { label: '5Y', value: '5Y' },
] as const;
